### ISSUE TITLE
Matrix Addition wrongly throws dimension error

### ISSUE THREAD

**Issue by discochance** [emin63/pyfinite#1]
Let's Suppose you're Adding two 6x1 matrices. Then
` if (self.cols != other.rows):
raise ValueError("dimension mismatch"):` 
At line `284 `triggers a dimension Mismatch even though the addition is correct. It should be the same as it is with subtraction at line `293`.

Kind regards

**Comment by emin63** [comment]
Thank you for catching that and suggesting the fix.

I confirmed the error, created a new test in `genericmatrix.py` called `RandomAddTest` to check for this, fixed the error and pushed out release version 1.6 to pypi.

Thank you very much for catching this.
