### ISSUE TITLE
Division returning NaN when 0/N

### ISSUE THREAD

**Issue by GonzaloHirschToptal** [emin63/pyfinite#12]
The `field.Division` method returns NaN when trying to call it using 0 as the first parameter (not dividing). This behaviour should instead be returning 0 in this case. This only happens when operations are performed using a LUT.

Steps to reproduce:
`F = ffield.FField(8, gen=355, useLUT=1)`
`F.Divide(0,10)`

**Comment by emin63** [comment]
Thanks. Confirmed, fixed in pull request #13 with accompanying unit tests and pushed as release 1.9.
