### ISSUE TITLE
F.Add in pyfinite/ffield

### ISSUE THREAD

**Issue by lmiclet** [emin63/pyfinite#17]
I try to use pyfinite/ffield and i got this strange result
******************************************************************
Program
*************************************
from pyfinite import ffield
F = ffield.FField(5) # create the field GF(2^5)
a = 7    # field elements are denoted as integers from 0 to 2^5-1
b = 2
print('a,b,a+b,F.Add(a,b),F.Subtract(a,b)',a,b,a+b,F.Add(a,b),F.Subtract(a,b))
***********************************************************************
Result
**********************************************
a,b,a+b,F.Add(a,b),F.Subtract(a,b) 7 2 9 5 5

*****************************************************************************
F.Add acts exactly as F.Subtract, but I am not in the case of two element .
Am I missing something obvious ?

**Comment by lmiclet** [comment]
Forget that, I have a misinterpretation of the whole package.
Sorry

**Comment by emin63** [comment]
Take a look at something like the Wikipedia page discussing fields of characteristic 2: https://en.m.wikipedia.org/wiki/GF(2) or just try the software with the field GF(2).

Using the ShowPolynomial function to see the elements represented as polynomials may also help. Basically both the Add and Subtract methods are like doing XOR on Boolean vectors so Add and Subtract are the same.

The main interesting thing to do with fields of characteristic 2 is multiplication and division.
