### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by adipokala** [emin63/pyfinite#5]
Collecting pyfinite
  Downloading https://files.pythonhosted.org/packages/ca/d3/c836cdb45006961c7917572d9673a0bd9e9e241df264cccca96cbbca1221/pyfinite-1.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ogDQQp/pyfinite/setup.py", line 30, in <module>
        long_description=get_readme(),
      File "/tmp/pip-build-ogDQQp/pyfinite/setup.py", line 21, in get_readme
        with open(path.join(here, 'README.rst'), encoding='utf-8') as my_fd:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ogDQQp/pyfinite/

**Comment by mhgharieb** [comment]
This problem is solved in the current version. Please, download the github version. It is the most updated version

**Comment by adipokala** [comment]
Thank You very much for your message. Are you planning to make a new release on pypi?

**Comment by emin63** [comment]
Thank you both for the commentary. When I did `pip install pyfinite`, it works fine for me from the current release.

@adipokala : what version of python are you using (e.g., can you try `python --version` and include what it reports)?

**Comment by adipokala** [comment]
@emin63 Thank You for your message. I was using pip for python2.7 and it failed. When I used pip for python3.7 then it worked.
