### ISSUE TITLE
method Transpose return type None

### ISSUE THREAD

**Issue by GerfautGE** [emin63/pyfinite#9]
it seems like Transpose method in genericmatrix returns None.

**Comment by emin63** [comment]
> 
> 
> it seems like Transpose method in genericmatrix returns None.

Yes. Transpose works "in place". It modifies the matrix itself. There is a decent argument that it could return the modified matrix but that behavior could confuse people into thinking the operation is not "in place". If you really want the return value, you could either write a new method (e.g., `transposed_copy`) or something like that.

Pull requests with that approach or others are welcome.
